//! Talking to the local Freenet core.
//!
//! The UI reaches the network only through the node running on the same
//! machine, over a WebSocket. Everything here is about turning app-level
//! intentions ("publish this game", "watch the lobby") into the five
//! operations the platform offers: PUT, GET, UPDATE, SUBSCRIBE, CONNECT.

use chess_core::game::ChessGameParametersV1;
use chess_core::identity::GameId;
use chess_core::lobby::LobbyParametersV1;
use ed25519_dalek::VerifyingKey;
use freenet_stdlib::client_api::{ClientRequest, ContractRequest, DelegateRequest, WebApi};
use freenet_stdlib::prelude::{
    ApplicationMessage, CodeHash, ContractCode, ContractContainer, ContractInstanceId, ContractKey,
    ContractWasmAPIVersion, Delegate, DelegateCode, DelegateContainer, DelegateKey,
    DelegateWasmAPIVersion, InboundDelegateMsg, Parameters, RelatedContracts, State, StateDelta,
    UpdateData, WrappedContract, WrappedState,
};
use std::sync::Arc;

/// The game contract's WASM, embedded at build time.
///
/// Only this one is carried: every game is a *new* contract instance, and a
/// PUT needs the module itself. See `build.rs` for why the others are not.
pub const GAME_WASM: &[u8] = include_bytes!(concat!(env!("CHESS_WASM_DIR"), "/game_contract.wasm"));

/// The delegate's WASM. Registering it requires the module itself.
pub const DELEGATE_WASM: &[u8] =
    include_bytes!(concat!(env!("CHESS_WASM_DIR"), "/chess_delegate.wasm"));

// Code hashes of the contracts the client only reads. Generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/contract_hashes.rs"));

/// Derive an instance id from a code hash and parameters.
///
/// Mirrors the network's own derivation, `BLAKE3(code_hash ‖ params)`, which
/// is what lets a client address a contract it does not carry the code for.
fn instance_id_from_hash(code_hash: &[u8; 32], params: &[u8]) -> ContractInstanceId {
    let mut hasher = blake3::Hasher::new();
    hasher.update(code_hash);
    hasher.update(params);
    let mut id = [0u8; 32];
    id.copy_from_slice(hasher.finalize().as_bytes());
    ContractInstanceId::new(id)
}

/// CBOR-encode contract parameters.
pub fn encode<T: serde::Serialize>(value: &T) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    ciborium::ser::into_writer(value, &mut out).map_err(|e| e.to_string())?;
    Ok(out)
}

pub fn decode<T: serde::de::DeserializeOwned>(bytes: &[u8]) -> Result<T, String> {
    ciborium::de::from_reader(bytes).map_err(|e| e.to_string())
}

/// A contract instance the UI wants to talk to: its code plus its parameters.
#[derive(Clone)]
pub struct Instance {
    pub contract: WrappedContract,
}

impl Instance {
    fn build(wasm: &'static [u8], params: Vec<u8>) -> Instance {
        let code = Arc::new(ContractCode::from(wasm.to_vec()));
        Instance {
            contract: WrappedContract::new(code, Parameters::from(params)),
        }
    }

    pub fn key(&self) -> ContractKey {
        *self.contract.key()
    }

    pub fn id(&self) -> ContractInstanceId {
        *self.contract.key().id()
    }

    pub fn container(&self) -> ContractContainer {
        ContractContainer::Wasm(ContractWasmAPIVersion::V1(self.contract.clone()))
    }
}

/// The lobby's instance id.
///
/// The lobby is a singleton published once by the deployer, so the client only
/// GETs, SUBSCRIBEs and UPDATEs it — none of which need the module, just the
/// key.
pub fn lobby_id() -> Result<ContractInstanceId, String> {
    let params = encode(&LobbyParametersV1::default())?;
    Ok(instance_id_from_hash(&LOBBY_CONTRACT_CODE_HASH, &params))
}

/// The lobby's full contract key, for UPDATE requests.
///
/// Built from the instance id and the code hash directly, which is the same
/// key `from_params_and_code` would produce — without needing the module.
pub fn lobby_key() -> Result<ContractKey, String> {
    Ok(ContractKey::from_id_and_code(
        lobby_id()?,
        CodeHash::new(LOBBY_CONTRACT_CODE_HASH),
    ))
}

/// One game's instance.
pub fn game_instance(creator: VerifyingKey, game_id: GameId) -> Result<Instance, String> {
    let params = encode(&ChessGameParametersV1 { creator, game_id })?;
    Ok(Instance::build(GAME_WASM, params))
}

/// PUT a contract with its initial state, subscribing in the same request so
/// no update can slip through between publishing and subscribing.
pub fn put_request(instance: &Instance, state: Vec<u8>, subscribe: bool) -> ClientRequest<'static> {
    ContractRequest::Put {
        contract: instance.container(),
        state: WrappedState::new(state),
        related_contracts: RelatedContracts::default(),
        subscribe,
        // Don't hold the request open waiting for the subscription to be
        // acknowledged: the UI is event-driven and reacts to the notification
        // when it arrives.
        blocking_subscribe: false,
    }
    .into()
}

/// Push a delta. Deltas rather than full state: the peers merge it under the
/// contract's own rules, which is both cheaper and what makes concurrent
/// updates converge.
pub fn update_request(key: ContractKey, delta: Vec<u8>) -> ClientRequest<'static> {
    ContractRequest::Update {
        key,
        data: UpdateData::Delta(StateDelta::from(delta)),
    }
    .into()
}

/// Push a whole state — used for the first write to a contract that may
/// already exist on the network, where we have no summary to diff against.
pub fn update_state_request(key: ContractKey, state: Vec<u8>) -> ClientRequest<'static> {
    ContractRequest::Update {
        key,
        data: UpdateData::State(State::from(state)),
    }
    .into()
}

pub fn get_request(id: ContractInstanceId, subscribe: bool) -> ClientRequest<'static> {
    ContractRequest::Get {
        key: id,
        return_contract_code: false,
        subscribe,
        blocking_subscribe: false,
    }
    .into()
}

pub fn subscribe_request(id: ContractInstanceId) -> ClientRequest<'static> {
    ContractRequest::Subscribe {
        key: id,
        summary: None,
    }
    .into()
}

/// WebSocket URL of the local node.
///
/// Derived from the page's own origin rather than hardcoded, because the app is
/// served *by* the node — on whatever port that node listens on. Hardcoding
/// 7509 breaks the moment someone runs a second node, which is exactly what the
/// two-node test does.
pub fn node_ws_url() -> String {
    let window = web_sys::window().expect("a browser window");
    let location = window.location();
    let host = location
        .host()
        .unwrap_or_else(|_| "127.0.0.1:7509".to_string());
    let secure = location.protocol().map(|p| p == "https:").unwrap_or(false);
    let scheme = if secure { "wss" } else { "ws" };
    format!("{scheme}://{host}/v1/contract/command?encodingProtocol=native")
}

/// Open the WebSocket and start the API client.
pub fn connect(
    on_response: impl FnMut(
            Result<
                freenet_stdlib::client_api::HostResponse,
                freenet_stdlib::client_api::ClientError,
            >,
        ) + 'static,
    on_error: impl FnMut(freenet_stdlib::client_api::Error) + Clone + 'static,
    on_open: impl FnOnce() + 'static,
) -> Result<WebApi, String> {
    let socket = web_sys::WebSocket::new(&node_ws_url())
        .map_err(|e| format!("could not open a websocket to the node: {e:?}"))?;
    Ok(WebApi::start(socket, on_response, on_error, on_open))
}

// ------------------------------------------------------------------ delegate

/// The delegate, built from the embedded module. Its key comes from the
/// constructed value rather than being derived by hand.
fn delegate() -> Delegate<'static> {
    let code = DelegateCode::from(DELEGATE_WASM.to_vec());
    Delegate::from((&code, &Parameters::from(vec![])))
}

/// The delegate's key.
pub fn delegate_key() -> DelegateKey {
    delegate().key().clone()
}

/// Register the delegate with the local node.
///
/// Idempotent: registering an already-registered delegate is harmless, so this
/// runs on every startup rather than needing to track whether it happened.
pub fn register_delegate_request() -> ClientRequest<'static> {
    DelegateRequest::RegisterDelegate {
        delegate: DelegateContainer::Wasm(DelegateWasmAPIVersion::V1(delegate())),
        // Ignored by the node since freenet-core#4140 (secrets are sealed
        // client-side); present only because the variant requires them.
        cipher: [0u8; 32],
        nonce: [0u8; 24],
    }
    .into()
}

/// Send an application message to the delegate.
pub fn delegate_request(payload: Vec<u8>) -> ClientRequest<'static> {
    DelegateRequest::ApplicationMessages {
        key: delegate_key(),
        params: Parameters::from(vec![]),
        inbound: vec![InboundDelegateMsg::ApplicationMessage(
            ApplicationMessage::new(payload),
        )],
    }
    .into()
}
