//! The `ContractInterface` body shared by every FreeChess contract.
//!
//! All four contracts (game, lobby, archive, player) have identical plumbing:
//! decode CBOR, hand off to the `ComposableState` implementation generated by
//! `#[composable]`, re-encode. Only the state and parameter types differ, so
//! that plumbing lives here once, generic over both.
//!
//! Writing it once matters beyond tidiness: these functions decide what a peer
//! accepts into replicated state, and a subtle divergence between four
//! copy-pasted versions is exactly the kind of bug that surfaces as "some peers
//! disagree about the state" long after deployment.

use ciborium::{de::from_reader, ser::into_writer};
use freenet_scaffold::ComposableState;
use freenet_stdlib::prelude::*;
use serde::{de::DeserializeOwned, Serialize};

/// Decode CBOR with a contract-shaped error.
fn decode<T: DeserializeOwned>(bytes: &[u8], what: &str) -> Result<T, ContractError> {
    from_reader::<T, &[u8]>(bytes)
        .map_err(|e| ContractError::Deser(format!("failed to decode {what}: {e}")))
}

fn encode<T: Serialize>(value: &T, what: &str) -> Result<Vec<u8>, ContractError> {
    let mut out = Vec::new();
    into_writer(value, &mut out)
        .map_err(|e| ContractError::Deser(format!("failed to encode {what}: {e}")))?;
    Ok(out)
}

/// Shared `validate_state`.
///
/// An empty state is accepted: that is what a contract looks like between
/// creation and its first PUT. Everything else must satisfy the state's own
/// `verify`, which checks every signature and every quota from the bytes alone
/// — no trust in the peer that delivered them.
pub fn validate<S, P>(
    parameters: Parameters<'static>,
    state: State<'static>,
) -> Result<ValidateResult, ContractError>
where
    S: ComposableState<ParentState = S, Parameters = P> + DeserializeOwned,
    P: DeserializeOwned,
{
    let bytes = state.as_ref();
    if bytes.is_empty() {
        return Ok(ValidateResult::Valid);
    }
    let state: S = decode(bytes, "state")?;
    let parameters: P = decode(parameters.as_ref(), "parameters")?;

    state
        .verify(&state, &parameters)
        .map(|_| ValidateResult::Valid)
        .map_err(|e| ContractError::InvalidUpdateWithInfo {
            reason: format!("state verification failed: {e}"),
        })
}

/// Shared `update_state`.
///
/// Merges each incoming update into the current state. Both paths run the
/// contract's own merge, so an update that would produce invalid state is
/// rejected here rather than propagating.
pub fn update<S, P>(
    parameters: Parameters<'static>,
    state: State<'static>,
    data: Vec<UpdateData<'static>>,
) -> Result<UpdateModification<'static>, ContractError>
where
    S: ComposableState<ParentState = S, Parameters = P>
        + DeserializeOwned
        + Serialize
        + Clone
        + Default,
    P: DeserializeOwned,
{
    let parameters: P = decode(parameters.as_ref(), "parameters")?;
    // An empty current state is the starting point for a brand-new contract.
    let mut current: S = if state.as_ref().is_empty() {
        S::default()
    } else {
        decode(state.as_ref(), "state")?
    };

    for update in data {
        match update {
            UpdateData::State(new_state) => {
                let incoming: S = decode(new_state.as_ref(), "incoming state")?;
                current
                    .merge(&current.clone(), &parameters, &incoming)
                    .map_err(|e| ContractError::InvalidUpdateWithInfo {
                        reason: e.to_string(),
                    })?;
            }
            UpdateData::Delta(delta) => {
                if delta.as_ref().is_empty() {
                    continue;
                }
                let delta: <S as ComposableState>::Delta = decode(delta.as_ref(), "delta")?;
                current
                    .apply_delta(&current.clone(), &parameters, &Some(delta))
                    .map_err(|e| ContractError::InvalidUpdateWithInfo {
                        reason: e.to_string(),
                    })?;
            }
            UpdateData::StateAndDelta { state, delta } => {
                let incoming: S = decode(state.as_ref(), "incoming state")?;
                current
                    .merge(&current.clone(), &parameters, &incoming)
                    .map_err(|e| ContractError::InvalidUpdateWithInfo {
                        reason: e.to_string(),
                    })?;
                if !delta.as_ref().is_empty() {
                    let delta: <S as ComposableState>::Delta = decode(delta.as_ref(), "delta")?;
                    current
                        .apply_delta(&current.clone(), &parameters, &Some(delta))
                        .map_err(|e| ContractError::InvalidUpdateWithInfo {
                            reason: e.to_string(),
                        })?;
                }
            }
            // `UpdateData` is `#[non_exhaustive]` as of freenet-stdlib 0.6, and
            // none of these contracts read related contracts. Rejecting is
            // recoverable and gives a clear diagnostic; panicking inside
            // contract WASM would take down the runtime for this instance.
            _ => return Err(ContractError::InvalidUpdate),
        }
    }

    Ok(UpdateModification::valid(
        encode(&current, "updated state")?.into(),
    ))
}

/// Shared `summarize_state`.
pub fn summarize<S, P>(
    parameters: Parameters<'static>,
    state: State<'static>,
) -> Result<StateSummary<'static>, ContractError>
where
    S: ComposableState<ParentState = S, Parameters = P> + DeserializeOwned,
    P: DeserializeOwned,
    <S as ComposableState>::Summary: Serialize,
{
    if state.as_ref().is_empty() {
        return Ok(StateSummary::from(Vec::new()));
    }
    let parameters: P = decode(parameters.as_ref(), "parameters")?;
    let state: S = decode(state.as_ref(), "state")?;
    let summary = state.summarize(&state, &parameters);
    Ok(StateSummary::from(encode(&summary, "summary")?))
}

/// Shared `get_state_delta`: what the requesting peer is missing.
pub fn get_delta<S, P>(
    parameters: Parameters<'static>,
    state: State<'static>,
    summary: StateSummary<'static>,
) -> Result<StateDelta<'static>, ContractError>
where
    S: ComposableState<ParentState = S, Parameters = P> + DeserializeOwned + Default,
    P: DeserializeOwned,
    <S as ComposableState>::Summary: DeserializeOwned,
    <S as ComposableState>::Delta: Serialize,
{
    if state.as_ref().is_empty() {
        return Ok(StateDelta::from(Vec::new()));
    }
    let state: S = decode(state.as_ref(), "state")?;
    let parameters: P = decode(parameters.as_ref(), "parameters")?;
    // An empty summary is what a peer holding no state produces, so answer it
    // with the delta against an empty state — i.e. everything we have. The
    // `Summary` type is generated by `#[composable]` and has no `Default`, so
    // derive that "I have nothing" summary by summarizing an empty state.
    let summary: <S as ComposableState>::Summary = if summary.as_ref().is_empty() {
        let empty = S::default();
        empty.summarize(&empty, &parameters)
    } else {
        decode(summary.as_ref(), "summary")?
    };

    match state.delta(&state, &parameters, &summary) {
        Some(delta) => Ok(StateDelta::from(encode(&delta, "delta")?)),
        None => Ok(StateDelta::from(Vec::new())),
    }
}
