//! Embeds contract identity into the UI — code where it is needed, hashes
//! where it is not.
//!
//! A client can only PUT a *new* contract instance if it carries the code:
//! the key is `BLAKE3(BLAKE3(wasm) ‖ params)` and the network needs the module
//! to validate anything stored under it. Every game is a new instance, so the
//! game contract's WASM has to ship in the bundle.
//!
//! The lobby is different. It is a singleton published once by the deployer, so
//! clients only ever GET, SUBSCRIBE and UPDATE it — none of which need the
//! code, only the key. Since the key derives from `BLAKE3(code_hash ‖ params)`,
//! embedding the 32-byte hash is enough.
//!
//! That distinction is worth ~450 KB of bundle. It matters more than it
//! sounds: the whole UI ships as a single contract state, and a large state
//! transfers by streaming, which is markedly less reliable across the public
//! network than a small one. An over-stuffed bundle does not merely load
//! slowly — it fails to arrive at all.

use std::path::PathBuf;

/// Contracts whose full WASM must be in the bundle, because clients create new
/// instances of them.
const EMBEDDED: [&str; 1] = ["game_contract"];

/// The delegate's WASM. Registering a delegate requires its module, and the
/// delegate is not optional: it is the only storage that survives a reload,
/// because the gateway sandboxes the app without `allow-same-origin` and
/// `localStorage` therefore throws.
const DELEGATE: &str = "chess_delegate";

/// Contracts the client only ever reads or updates. Their code hash is enough
/// to derive the key.
const HASH_ONLY: [&str; 1] = ["lobby_contract"];

fn main() {
    let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("ui/ has a parent")
        .to_path_buf();
    let wasm_dir = workspace.join("target/wasm32-unknown-unknown/release");

    let require = |name: &str| -> PathBuf {
        let path = wasm_dir.join(format!("{name}.wasm"));
        if !path.exists() {
            panic!(
                "missing {}\n\n\
                 The UI needs the contracts built first:\n\
                 \n    cargo make build-contracts\n",
                path.display()
            );
        }
        println!("cargo:rerun-if-changed={}", path.display());
        path
    };

    for name in EMBEDDED {
        require(name);
    }
    require(DELEGATE);

    // Emit the code hash of each read-only contract as a Rust array literal.
    // This is the same hash the network derives the key from, so the client
    // reaches the exact instance the deployer published — without carrying the
    // module.
    let mut generated =
        String::from("// Generated by build.rs. Code hashes of contracts the client never PUTs.\n");
    for name in HASH_ONLY {
        let path = require(name);
        let wasm = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("could not read {}: {e}", path.display()));
        let hash = blake3::hash(&wasm);
        let const_name = name.to_uppercase().replace('-', "_");
        generated.push_str(&format!(
            "pub const {const_name}_CODE_HASH: [u8; 32] = {:?};\n",
            hash.as_bytes()
        ));
    }

    let out =
        PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set")).join("contract_hashes.rs");
    std::fs::write(&out, generated).expect("could not write generated hashes");

    println!("cargo:rustc-env=CHESS_WASM_DIR={}", wasm_dir.display());
    println!("cargo:rerun-if-changed=build.rs");
}
